# fly.toml app configuration file generated for qrgods on 2023-09-30T02:37:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qrgods"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5176
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
